# Generated by Django 4.0.4 on 2022-10-12 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_name', models.TextField(unique=True)),
                ('social_link', models.URLField(max_length=128)),
            ],
        ),
    ]
