# Generated by Django 4.0.4 on 2022-10-19 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='stage_name',
            new_name='name',
        ),
    ]
