# Generated by Django 4.0.4 on 2022-10-19 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0002_alter_album_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
