# Generated by Django 4.0.4 on 2022-10-19 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0003_album_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='approved',
            field=models.BooleanField(default=False, help_text='Approve the album if its name is not explicit'),
        ),
    ]
