# Generated by Django 4.0.4 on 2022-10-28 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0005_alter_album_creation_date_alter_album_release_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=255)),
                ('audio', models.FileField(help_text='Allowed type - .mp3, .wav', upload_to='songs/')),
                ('image', models.ImageField(default='images/def.jpg', upload_to='images/')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='albums.album')),
            ],
        ),
    ]
